### ISSUE TITLE
ImportError: cannot import name '_ellipsoid'

### ISSUE THREAD

**Issue by BeyondHeaven** [hellochick/ICNet-tensorflow#33]
I get this error. What is the version of scipy?
```
Traceback (most recent call last):
  File "inference.py", line 10, in <module>
    from scipy import misc
  File "/home/media/ruodai/code/anaconda/lib/python3.6/site-packages/scipy/misc/__init__.py", line 67, in <module>
    from scipy.interpolate._pade import pade as _pade
  File "/home/media/ruodai/code/anaconda/lib/python3.6/site-packages/scipy/interpolate/__init__.py", line 175, in <module>
    from .interpolate import *
  File "/home/media/ruodai/code/anaconda/lib/python3.6/site-packages/scipy/interpolate/interpolate.py", line 21, in <module>
    import scipy.special as spec
  File "/home/media/ruodai/code/anaconda/lib/python3.6/site-packages/scipy/special/__init__.py", line 648, in <module>
    from ._ellip_harm import ellip_harm, ellip_harm_2, ellip_normal
  File "/home/media/ruodai/code/anaconda/lib/python3.6/site-packages/scipy/special/_ellip_harm.py", line 7, in <module>
    from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
ImportError: cannot import name '_ellipsoid'
```

**Comment by BeyondHeaven** [comment]
I have resolved this by  
```
cd PATH-TO-YOUR-ANACONDA
./bin/pip install --upgrade --force-reinstall scipy
```
